-- 코드를 입력하세요
WITH RECURSIVE HOUR AS(
    SELECT 0 AS hour
    UNION ALL
    SELECT hour+1
    FROM HOUR
    WHERE hour<23
)
SELECT H.hour AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOUR H LEFT JOIN ANIMAL_OUTS A
ON HOUR(A.DATETIME) = H.hour
GROUP BY H.hour
ORDER BY HOUR;