-- 코드를 작성해주세요
SELECT COUNT(ID) FISH_COUNT, CONVERT(DATE_FORMAT(TIME,'%m'),UNSIGNED) MONTH
FROM FISH_INFO
GROUP BY CONVERT(DATE_FORMAT(TIME,'%m'),UNSIGNED)
ORDER BY CONVERT(DATE_FORMAT(TIME,'%m'),UNSIGNED);