-- 코드를 입력하세요
SELECT B.INGREDIENT_TYPE
     , SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
  FROM ICECREAM_INFO AS B JOIN FIRST_HALF AS A ON B.FLAVOR = A.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY A.TOTAL_ORDER ASC;