-- 코드를 입력하세요
SELECT A.CATEGORY CATEGORY, SUM(B.SALES) TOTAL_SALES
FROM BOOK A JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
HAVING SUM(SALES)
ORDER BY CATEGORY;