-- 코드를 작성해주세요
WITH MAIN AS(
    SELECT D.ID, D.EMAIL,GROUP_CONCAT(S.NAME) NAME,GROUP_CONCAT(S.CATEGORY) CATEGORY
    FROM DEVELOPERS D JOIN SKILLCODES S
    ON D.SKILL_CODE & S.CODE = S.CODE
    GROUP BY D.ID, D.EMAIL
)
SELECT * 
FROM (
    SELECT 
    CASE 
    WHEN NAME LIKE '%Python%' AND CATEGORY LIKE '%Front End%' THEN 'A'
    WHEN NAME LIKE '%C#%' THEN 'B'
    WHEN CATEGORY LIKE '%Front End%' THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
    FROM MAIN
) A
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;